# Generated by Django 4.1.10 on 2023-08-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=250, unique=True)),
                ('Email', models.EmailField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Reg_Table',
            },
        ),
    ]
