# Generated by Django 4.1.10 on 2023-08-19 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=250, unique=True)),
                ('DOB', models.EmailField(max_length=250)),
                ('Adress', models.CharField(max_length=250)),
                ('userId', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to='app.regmodel')),
            ],
            options={
                'db_table': 'Profile_Table',
            },
        ),
    ]
