# Generated by Django 4.1.10 on 2023-08-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='DOB',
            field=models.CharField(max_length=250),
        ),
    ]
